erts: Add support for encrypting crash dumps

diff --git a/lib/crypto/configure b/lib/crypto/configure
--- a/lib/crypto/configure
+++ b/lib/crypto/configure
@@ -643,9 +643,9 @@ enable_year2038=yes
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
 CRYPTO_NO_DEPRECATE_WARN
+CRYPTO_DISABLE_EVP_HMAC
+CRYPTO_DISABLE_EVP_DH
 DISABLE_OTP_TEST_ENGINE
-DISABLE_EVP_HMAC
-DISABLE_EVP_DH
 SSL_DYNAMIC_ONLY
 SSL_DED_LD_RUNTIME_LIBRARY_PATH
 SSL_EXTRA_LIBS
@@ -4658,6 +4658,14 @@ fi
 
 
 
+
+no_werror_CFLAGS=$(echo " $CFLAGS " | sed 's/ -Werror / /g')
+if test "X $CFLAGS " != "X$no_werror_CFLAGS"; then
+   CFLAGS="$no_werror_CFLAGS"
+   WERRORFLAGS=-Werror
+fi
+
+
 ac_header= ac_cache=
 for ac_item in $ac_header_c_list
 do
@@ -6872,24 +6880,6 @@ fi
 
 
 
-{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for multiarch directory" >&5
-printf %s "checking for multiarch directory... " >&6; }
-multiarch_dir=
-if test "$GCC" = "yes"; then
-   multiarch_dir=`$CC $CFLAGS -print-multiarch 2>/dev/null`
-   if test $? -ne 0; then
-     multiarch_dir=
-   fi
-fi
-if test "$multiarch_dir" = ""; then
-   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: not found" >&5
-printf "%s\n" "not found" >&6; }
-else
-   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $multiarch_dir" >&5
-printf "%s\n" "$multiarch_dir" >&6; }
-fi
-
-
 # The cast to long int works around a bug in the HP C Compiler
 # version HP92453-01 B.11.11.23709.GP, which incorrectly rejects
 # declarations like 'int a3[[(sizeof (unsigned char)) >= 0]];'.
@@ -6924,6 +6914,24 @@ printf "%s\n" "$ac_cv_sizeof_void_p" >&6; }
 
 printf "%s\n" "#define SIZEOF_VOID_P $ac_cv_sizeof_void_p" >>confdefs.h
 
+
+
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for multiarch directory" >&5
+printf %s "checking for multiarch directory... " >&6; }
+multiarch_dir=
+if test "$GCC" = "yes"; then
+   multiarch_dir=`$CC $CFLAGS -print-multiarch 2>/dev/null`
+   if test $? -ne 0; then
+     multiarch_dir=
+   fi
+fi
+if test "$multiarch_dir" = ""; then
+   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: not found" >&5
+printf "%s\n" "not found" >&6; }
+else
+   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $multiarch_dir" >&5
+printf "%s\n" "$multiarch_dir" >&6; }
+fi
 
 
 std_ssl_locations="\
@@ -7028,25 +7036,24 @@ fi
 if test ${enable_evp_dh+y}
 then :
   enableval=$enable_evp_dh;  case "$enableval" in
-    no)   DISABLE_EVP_DH=1;;
-    *)    DISABLE_EVP_DH=0;;
+    no)   CRYPTO_DISABLE_EVP_DH=1;;
+    *)    CRYPTO_DISABLE_EVP_DH=0;;
   esac
 else case e in #(
-  e) DISABLE_EVP_DH=0 ;;
+  e) CRYPTO_DISABLE_EVP_DH=0 ;;
 esac
 fi
-
 
 
 # Check whether --enable-evp-hmac was given.
 if test ${enable_evp_hmac+y}
 then :
   enableval=$enable_evp_hmac;  case "$enableval" in
-    no)   DISABLE_EVP_HMAC=1;;
-    *)    DISABLE_EVP_HMAC=0;;
+    no)   CRYPTO_DISABLE_EVP_HMAC=1;;
+    *)    CRYPTO_DISABLE_EVP_HMAC=0;;
   esac
 else case e in #(
-  e) DISABLE_EVP_HMAC=0 ;;
+  e) CRYPTO_DISABLE_EVP_HMAC=0 ;;
 esac
 fi
 
@@ -9095,10 +9102,8 @@ LDFLAGS="$saveLDFLAGS"
 LIBS="$saveLIBS"
 
 
-no_werror_CFLAGS=$(echo " $CFLAGS " | sed 's/ -Werror / /g')
-if test "X $CFLAGS " != "X$no_werror_CFLAGS"; then
-   CFLAGS="$no_werror_CFLAGS"
-   WERRORFLAGS=-Werror
+if test "x$GCC" = xyes; then
+    CFLAGS="$WERRORFLAGS $CFLAGS"
 fi
 
 
@@ -9114,6 +9119,13 @@ fi
 
 
 
+
+
+
+
+if test "x$GCC" = xyes; then
+    CFLAGS="$WERRORFLAGS $CFLAGS"
+fi
 
 ac_config_files="$ac_config_files c_src/$host/Makefile:c_src/Makefile.in"
 
